/*
 * Nation States - a map game where every U.S. state becomes its own nation.
 *
 * THIS FILE IS THE BOOT AND THE SHARED STATE. Everything else that used to be
 * here is now beside it (M10.0), split along the seams this file's own comment
 * banners already marked:
 *
 *   js/app.js       the store, the data fetch, init(), who you are
 *   js/map.js       the d3 map: building it, colouring it, hovering, selecting
 *   js/shell.js     the chrome around the map: controls, modal, toast, the turn
 *                   banner and the turn flow, the end screen, the timeline
 *   js/panels.js    every render* function that fills the right-hand panel
 *   js/format.js    fmtPop / fmtGdp / escapeHtml
 *
 * They are still one classic-script scope, so nothing changed about who can
 * call what — this is a filing decision, not an architectural one. It happens
 * NOW because M10 and M11 are about to add a journal, an objectives screen, a
 * generated reference and progressive disclosure to a sixteen-block panel, and
 * all of that is rendering: 2,400 lines was already the audit's "monolith
 * renderer on the far side of an otherwise clean model boundary", and 3,200
 * would have been worse to move.
 *
 * LOAD ORDER (index.html): app, map, shell, panels, format. Only one thing in
 * it is load-bearing — `init` is registered on DOMContentLoaded at the bottom
 * of app.js and everything it calls is a hoisted function declaration, so the
 * files may be reordered but not omitted.
 */

/*
 * Nation States - a map game where every U.S. state becomes its own nation.
 *
 * Rendering is driven by Game ownership: each county is filled with its owning
 * nation's color, and the heavy borders are the boundaries between nations. As
 * actions move counties around, the map re-renders from the model.
 */

const WIDTH = 975;
const HEIGHT = 610;

// Connecticut's old counties still live in the base geometry. The mapping and
// the reasoning live in js/geo-ct.js so tests/ can reach them; boot-globals.js
// publishes the module as window.GeoCT.
//
// BOUND IN init(), NOT HERE. boot-globals.js is a deferred module, so it has not
// run yet while this classic script is being evaluated. Reading an ESM-bridged
// global at top level is a load-time TypeError.
let OLD_CT_TO_REGION = null;
let OLD_CT = null;

const store = {
  mode: 'nations', // 'nations' | 'counties'
  colorMode: 'standard', // 'standard' | 'political' | 'gdp' | 'population'
  data: null,
  topo: null,
  path: null,
  g: null,
  svg: null,
  hoverShape: null,
  selectShape: null,
  actionLayer: null,
  countyPaths: null,
  nationBorders: null,
  countyById: new Map(),
  outlineCache: new Map(),
  selectGlow: null,
  hoverKey: null, // what the hover outline currently shows; the mousemove guard
  selected: null, // { level:'nation'|'county', id }
  rng: null,      // seeded RNG for this session (js/rng.js); serialized in the save
  seed: null,
  // ?dev=1 exposes the manual world-step control. M5 grows the dashboard and the
  // 50-turn simulator out of the same flag.
  dev: new URLSearchParams(location.search).has('dev'),
};

/* ------------------------------------------------------------------ */
/* boot                                                                */
/* ------------------------------------------------------------------ */
/*
 * Fetch a baked JSON file, never from the HTTP cache.
 *
 * `data/*.json` is regenerated by the scripts in build/, and a browser that
 * replays a stale copy runs the game against a world that no longer exists —
 * silently, and with no way to tell from inside the page. That is not
 * hypothetical: a cache entry written before the dev server started sending
 * no-store survived every reload, so the game kept booting Hawaii with no
 * adjacency and sixteen movements instead of twenty-four, hours after the bake.
 *
 * This is what the hand-bumped `?v=` query strings in index.html were reaching
 * for. `cache: 'no-store'` says it once, correctly, and needs no maintenance.
 */
const getJSON = (path, fallback) =>
  fetch(path, { cache: 'no-store' })
    .then((r) => {
      if (!r.ok) throw new Error(`${path}: HTTP ${r.status}`);
      return r.json();
    })
    .catch((err) => {
      if (fallback === undefined) throw err;  // required file: fail the boot loudly
      console.warn('optional data file unavailable:', err.message);
      return fallback;
    });

async function init() {
  try {
    const [topo, data, ctGeo, adjacency, neighbors, partyDefs, trade, areas, geoMode, economy, transport, cultureMode, tunables, ideologies, capitals, eventDefs, leaderDefs, nameDefs, scenarioDoc] = await Promise.all([
      getJSON('data/counties-10m.json'),
      getJSON('data/game-data.json'),
      getJSON('data/ct-planning-regions.geojson'),
      getJSON('data/adjacency.json'),
      getJSON('data/county_neighbors.json', {}),
      getJSON('data/parties.json', {}),
      getJSON('data/county_trade.json', null),
      getJSON('data/areas.json', null),
      getJSON('content/geographical.json', null),
      getJSON('data/economy.json', null),
      getJSON('data/transport.json', null),
      getJSON('content/cultural.json', null),
      getJSON('content/tunables.json', null),
      getJSON('content/ideologies.json', null),
      getJSON('content/capitals.json', null),
      getJSON('content/events.json', null),
      getJSON('content/leaders.json', null),
      getJSON('content/names.json', null),
      // The opening board. Optional: a build without it boots the fifty-one
      // states rather than failing, which is also what `?scenario=none` asks for.
      getJSON('content/scenario-shattered.json', null),
    ]);
    // The six ideologies, before anything reads a political value.
    Ideology.load(ideologies);
    // Authored tunable overrides, applied over the schema defaults in js/tunables.js.
    if (tunables) {
      const unknown = TUNE.load(tunables.values || tunables);
      if (unknown.length) console.warn('content/tunables.json: unknown keys ignored:', unknown);
    }
    /*
     * ...AND THE DIFFICULTY OVER THE TOP (M13.1). A preset is a modifier on the
     * shipped tuning rather than a replacement for it, so the authored file is
     * applied first and handed to `Telemetry.apply` to re-apply underneath.
     * `?difficulty=` overrides the remembered choice, which is how a playtest
     * hands somebody a specific setting by link.
     */
    store.authoredTune = tunables ? (tunables.values || tunables) : {};
    /*
     * The authored file is the shipped game's tuning, not somebody's override
     * (spec v2 §2.3). Telling TUNE that is what lets a save restore what it was
     * deliberately played with while still picking up an edit made to the file
     * since — which is the acceptance test for this phase.
     */
    TUNE.setAuthored(store.authoredTune);
    const wantDiff = new URLSearchParams(location.search).get('difficulty');
    Telemetry.apply(wantDiff || Telemetry.remembered(), store.authoredTune);
    /*
     * COMPLEXITY MODE (M?): Full or Economy, same precedence as difficulty.
     * `?complexity=` names it for this boot; a loaded save overrides this again
     * with what it was actually played with (see the resume path below).
     */
    store.complexity = Complexity.init({ url: new URLSearchParams(location.search).get('complexity') });
    // Seeded RNG, created before anything draws. Everything downstream takes it
    // explicitly; nothing reads it off a module global.
    //
    // `?seed=<whole number>` names the world instead of drawing one, which is
    // how the same opening gets played twice and how the New game dialog hands
    // a seed to the world it is about to start. Anything that is not a whole
    // number is ignored rather than coerced: a seed of NaN is a silently
    // different game every reload.
    const wantSeed = new URLSearchParams(location.search).get('seed');
    const namedSeed = wantSeed != null && /^-?\d+$/.test(wantSeed.trim())
      ? parseInt(wantSeed, 10) | 0
      : null;
    if (wantSeed != null && namedSeed == null) console.warn(`?seed=${wantSeed} is not a whole number; drawing one instead.`);
    store.seed = namedSeed != null ? namedSeed : RNG.newSeed();
    store.rng = RNG.create(store.seed);

    OLD_CT_TO_REGION = GeoCT.OLD_CT_TO_REGION;
    OLD_CT = GeoCT.OLD_CT;

    store.data = data;
    store.topo = topo;
    store.areasDef = areas; // the build stamp a save is validated against
    store.neighbors = neighbors; // Census County Adjacency File (fips -> [fips])
    store.trade = trade;         // offline-baked trade attributes (county_trade.json)
    store.transport = transport; // rail / interstates / Canada-Mexico gateways (transport.json)
    Ledger.reset();
    Relations.reset();
    Recognition.reset();
    Pacts.reset();
    Migration.reset();
    Coalitions.reset();
    Colors.assign(Object.keys(data.states));
    Game.init(data, adjacency, areas, { trade, transport, culture: cultureMode });
    /*
     * setup-only regional party spawns. NOT gated by `Complexity.enabled('movements')`:
     * the Shattered board's opening partition is BUILT from these seeded cores
     * (Scenario.apply founds each successor nation on its movement's core Areas),
     * so skipping the spawn breaks board generation itself, independent of the
     * complexity mode. Economy mode instead stops these movements from ever
     * growing or mattering again after this point — see the `movements` gates
     * in js/world.js (phaseSentiment/phaseSecession never run).
     */
    const emerged = Parties.setup(partyDefs, store.rng);
    MapModes.init(data);
    if (geoMode && geoMode.type === 'ns-mapmode') MapModes.setRegion(geoMode); // published in the editor
    if (cultureMode && cultureMode.type === 'ns-mapmode') MapModes.setCulture(cultureMode);
    if (economy) MapModes.setEconomy(economy); // baked six-sector production values
    if (economy) Market.update(TUNE); // opening market prices
    // The seats of government, resolved through the Area alias — several capital
    // counties are merged into a larger Area, and a raw FIPS lookup would miss
    // them silently (the M1.13 trap).
    if (capitals) Victory.load(capitals);
    Events.reset();
    if (eventDefs) Events.load(eventDefs);
    Leaders.reset();
    if (leaderDefs) Leaders.load(leaderDefs);
    // Loaded BEFORE Game.init, because the first thing a breakaway needs is a name.
    if (nameDefs) Identity.load(nameDefs);

    /*
     * THE OPENING BOARD (M8).
     *
     * PHASE A, and this is the only place it can go. After `Parties.setup`,
     * because the surgery wires movements to the countries they founded and
     * seeds corridor sentiment. Before `TurnSystem.begin`, or the successors are
     * never dealt a turn. Before `World.begin`, because the power stocks open AT
     * TARGET on whatever they see and `History.capture(0)` takes the timeline's
     * first frame — run the split afterwards and the timeline opens on an intact
     * Texas while eleven new nations climb from the floor for fifteen turns.
     *
     * `?scenario=none` is the way back to the fifty-one states; the default is
     * the shattered board, because that is what this game is about (D-M8a).
     */
    store.scenario = null;
    const wantScenario = new URLSearchParams(location.search).get('scenario');
    if (wantScenario !== 'none' && scenarioDoc && Scenario.load(scenarioDoc)) {
      try {
        store.scenario = Scenario.apply({
          doc: scenarioDoc, culture: cultureMode, rng: store.rng, tune: TUNE,
        });
      } catch (err) {
        /*
         * An authored partition that does not add up is a CONTENT bug, and the
         * honest response is a playable baseline game plus a message naming the
         * offending FIPS — not a blank map. The error text already names it.
         */
        console.error(err);
        setTimeout(() => flash('\u{26A0} The opening scenario could not be applied ('
          + escapeHtml(err.message) + '), so this is the fifty-one-state board.', 'warn',
        { news: true }), 300);
      }
    }

    TurnSystem.begin([...Game.nations.keys()], store.rng);
    choosePlayer();
    World.begin(TUNE, null, store.rng); // the power stocks and the leaders
    // PHASE B, strictly after World.begin: it calls Recognition.reset(), which
    // wipes both the granted matrix and the origins map, so anything phase A
    // wrote there would be gone without a trace (world.js, recognition.js:47).
    if (store.scenario) Scenario.afterBegin({ doc: scenarioDoc, rng: store.rng, tune: TUNE });
    if (emerged.length) {
      setTimeout(() => flash(`\u{1F5F3} Regional parties emerged: <strong>${emerged.map(escapeHtml).join('</strong>, <strong>')}</strong>.`, 'warn', { news: true }), 300);
    }
    Game.onChange(onGameChange);
    buildMap(topo, ctGeo);
    wireControls();

    /*
     * Resume from the live document if there is one.
     *
     * Done AFTER the map is built, because applying a document emits and the
     * renderer has to exist to hear it — and after a full fresh world has been
     * assembled, so a document that turns out to be unreadable leaves a playable
     * game rather than a blank map. `?fresh=1` skips the resume without deleting
     * anything; the Load dialog is where documents are managed deliberately.
     */
    let freshGame = true;
    if (!new URLSearchParams(location.search).has('fresh')) {
      const live = await SaveManager.readLive();
      if (live) {
        const res = SaveManager.apply(live);
        if (res.ok) {
          freshGame = false;
          flash('\u{1F4BE} Resumed at world turn <strong>' + World.getTurn() + '</strong> from '
            + 'data/state.json. Add <code>?fresh=1</code> to the URL to start over.', '');
        } else {
          console.warn('state.json was not loadable, starting fresh:', res.message);
          flash('\u{26A0} The saved world could not be resumed (' + escapeHtml(res.message)
            + ') so this is a fresh game.', 'warn', { news: true });
        }
      }
    }

    /*
     * A resumed document carries its own player; a document written before M6.2
     * carries none, and so does a fresh game whose `choosePlayer` ran against
     * the pre-resume world. Either way, settle it before the first sweep — a
     * sweep with no player declines to run, and the symptom would be a game that
     * simply never lets the AI move.
     */
    if (!Game.playerNation()) choosePlayer();
    // ...and hand the seat back to the human, wherever in the order the load left
    // the pointer.
    AI.sweep(TUNE, store.rng);

    // The player settles their own election result; see offerElection.
    World.setElectionDefer((nid) => Game.isPlayer(nid));
    Leaderboard.refresh();
    renderTurnBanner();
    // The journal reads the ledger and owns nothing, so it draws itself from
    // whatever the boot produced — a fresh world, a resumed one, or a scenario
    // whose opening entries are already the front page.
    if (typeof Journal !== 'undefined') Journal.reset();
    if (typeof Disclosure !== 'undefined') Disclosure.reset();
    // The recording starts when the world does, and takes its first row at
    // turn 0 so a session has a baseline to be measured against.
    Telemetry.reset();
    Telemetry.sample();
    /*
     * SAY SO, ONCE, IN THE GAME (M13.2).
     *
     * `?playtest=1` is what a build handed to a tester carries. The recording
     * itself runs either way — it is how the author's own runs get measured —
     * but a build being SENT to somebody says so on their first turn, in the
     * game, rather than relying on it having been mentioned in the email that
     * brought them here. Once per browser, because a notice that appears every
     * session is a notice nobody reads.
     */
    if (new URLSearchParams(location.search).has('playtest')) {
      let seen = false;
      try { seen = localStorage.getItem('ns_playtest_seen') === '1'; } catch (e) { /* fine */ }
      if (!seen) {
        try { localStorage.setItem('ns_playtest_seen', '1'); } catch (e) { /* fine */ }
        setTimeout(() => flash(
          '\u{1F4CA} <strong>This is a playtest build.</strong> It keeps a record of your session '
          + '&mdash; what happened, what you did, and how long turns took &mdash; so it can be sent '
          + 'back and read. Nothing leaves this tab until you choose '
          + '<strong>Menu &rarr; Export this session</strong>, and that screen lists exactly what '
          + 'is in the file.', 'warn', { news: true }), 1200);
      }
    }
    select('nation', you());
    document.getElementById('loading')?.remove();

    /*
     * The faction picker, for a genuinely new game only: not after a resume,
     * which already knows who you were, and not when `?play=` has answered the
     * question. `choosePlayer` has already seated somebody, so cancelling out of
     * this leaves a playable game rather than a blank one.
     */
    if (freshGame && !new URLSearchParams(location.search).get('play')) {
      showStart((nid) => {
        const r = Factions.choose(nid, TUNE);
        store.playerName = Game.playerNation() ? Game.playerNation().name : null;
        TurnSystem.seat(nid);
        Leaderboard.refresh();
        renderTurnBanner();
        setMode('nations');
        select('nation', nid);
        if (r) {
          flash(`\u{1F3DB}\u{FE0F} You are <strong>${escapeHtml(r.name)}</strong> — <strong>${escapeHtml(r.label)}</strong>. `
            + escapeHtml(r.blurb)
            + (r.bonus > 0 ? ` Opening grant <strong>${fmtGdp(r.bonus)}</strong>.` : ''), '');
        }
        openingEdition();
      });
    } else if (freshGame) {
      openingEdition();
    }
  } catch (err) {
    const el = document.getElementById('loading');
    if (el) el.textContent = 'Could not load map data. Start the local server with `python server.py` and reload (see README.md).';
    console.error(err);
  }
}

/*
 * WHO YOU ARE.
 *
 * M6.4 puts a faction picker in front of this. Until then the seat is assigned
 * from the seed — the nation at the head of the shuffled turn order — and
 * `?play=<id or name>` overrides it, which is how a particular situation gets
 * played twice. Assigning rather than asking is the deliberate choice for M6.2:
 * the milestone is about there BEING one seat, and a chooser landing in the same
 * commit would hide whether the seat works.
 */
function choosePlayer() {
  const wanted = new URLSearchParams(location.search).get('play');
  let pick = null;
  if (wanted) {
    const key = wanted.trim().toLowerCase();
    for (const [id, n] of Game.nations) {
      if (id === wanted || n.name.toLowerCase() === key) { pick = id; break; }
    }
    if (!pick) console.warn(`?play=${wanted} names no nation; falling back to the turn order.`);
  }
  Game.setPlayer(pick || TurnSystem.currentId());
  // Remembered for the defeat screen, which has to name a nation that no longer
  // exists — `Game.getPlayer()` keeps the id, but the name lives on the record.
  store.playerName = Game.playerNation() ? Game.playerNation().name : null;
  // ...and start the game on your own slot rather than sweeping the AI round to
  // reach it. A fresh world has not begun yet; nobody is owed a turn in it.
  TurnSystem.seat(Game.getPlayer());
}

/** The nation the human is playing. Null only in a world nobody is playing. */
const you = () => Game.getPlayer();

/*
 * WHO DO YOU WANT TO BE.
 *
 * Shown once, before a fresh game, and skipped entirely when `?play=` names a
 * seat or a saved document already knows who you were — a start screen that
 * appears in front of a game already in progress is a start screen nobody wants
 * to see twice.
 *
 * Every nation is listed, because restricting it to a curated two dozen would be
 * an arbitrary line through a map whose whole premise is that every state is a
 * country now. The tier does the steering instead, and it says WHY: "Rhode
 * Island's problem is room to grow — 0% of its neighbours are smaller" is a
 * sentence a new player can act on, where "hard" is not.
 */
function showStart(onPick) {
  const el = document.getElementById('startscreen');
  const card = el.querySelector('.start-card');
  const rated = Factions.list(TUNE);
  let filter = 'all';

  const draw = () => {
    const rows = rated.filter((r) => filter === 'all' || r.tier === filter);
    card.querySelector('.start-list').innerHTML = rows.map((r) => `
      <button class="fac" data-nid="${r.nid}">
        <span class="fac-top">
          <span class="dot" style="background:${r.color}"></span>
          <span class="nm">${escapeHtml(r.name)}</span>
          <span class="tier tier-${r.tier}">${escapeHtml(r.label)}</span>
        </span>
        <span class="why">${escapeHtml(r.summary)}</span>
        ${r.bonus > 0 ? `<span class="grant">Opening grant ${fmtGdp(r.bonus)}</span>` : ''}
      </button>`).join('');
    card.querySelectorAll('.fac').forEach((b) => {
      b.onclick = () => { el.classList.remove('show'); onPick(b.dataset.nid); };
    });
    card.querySelectorAll('.start-tabs button').forEach((b) => {
      b.classList.toggle('active', b.dataset.tier === filter);
    });
  };

  const tabs = [{ id: 'all', label: `All ${rated.length}` }]
    .concat(Factions.TIERS.slice().reverse().map((t) => ({
      id: t.id, label: `${t.label} (${rated.filter((r) => r.tier === t.id).length})`,
    })));

  card.innerHTML = `
    <h2>Choose a nation</h2>
    <p class="start-sub">Every U.S. state is its own country. Pick one and hold it together — or put
      the Union back. The map is the same whoever you play; a harder start begins with a larger
      treasury instead.</p>
    <div class="start-tabs">${tabs.map((t) =>
      `<button data-tier="${t.id}">${escapeHtml(t.label)}</button>`).join('')}</div>
    <div class="start-list"></div>`;
  card.querySelectorAll('.start-tabs button').forEach((b) => {
    b.onclick = () => { filter = b.dataset.tier; draw(); };
  });
  draw();
  el.classList.add('show');
}

/* The one line of load order that matters: everything init() calls is a
 * hoisted function declaration in the shared classic-script scope, so the
 * other files need only be present, not first. */
window.addEventListener('DOMContentLoaded', init);
